export const API_URL = 'https://api.themoviedb.org/3/';
export const API_KEY = '?api_key=92d590ff486c6a1d7e8d20b793c89a8a';
export const IMG_URL = 'https://image.tmdb.org/t/p/w342/';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';
